api_key: # <-- obtain your codePost API key from https://codepost.io/settings

# Course specific settings
course_name: COS999
course_period: S2019

# TigerFile specific settings
tigerfile_path: /n/fs/tigerfile/Files/{course_name}_{course_period}/{assignment_name}
user_pattern: "{}@princeton.edu"
partners_path: "{pwd}/partners.txt"
group_separator: "-"
notdone_file: "NOTDONE"

# RunScript specific settings (for COS 126, 226, etc.)
tests_path: "{pwd}/../.output/{submission}.output.txt"

# LMS column formatting (optional, for convenient CSV grade export, comment out if not using)
lms_format: "{name} |{id}"

# For each assignment, add an entry "Assignment name": <Blackboard column ID>
# You can locate the correct Blackboard column ID as indicated in:
# https://github.com/PrincetonUniversity/codePost-tools/blob/master/README.md#export-grades-to-csv-to-import-in-blackboard
lms_ids:
  "Hello": 38213
  "Loops": 38235
